name: frontend
description: Frontend of the progress bar server.
version: 0.1.0
homepage: https://progressbarserver.appspot.com/
author: Filip Hracek <email@example.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  angular: ^5.0.0-beta+2
  angular_components: ^0.9.0

dev_dependencies:
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.1
  sass_builder: ^2.1.1
  test: ^1.3.0
